language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
script:
  - yarn test:release && yarn build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: '10'
      script:
        - yarn build
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn semantic-release; fi
